Skip detail view chooser if only one detail view is available
Caleydo/ordino pull request #357
Opened 2022-02-11 10:17 UTC by oltionchampari

Closes datavisyn/ordino_bayer_indications#90

### Summary 
* Added logic to skip detail view chooser if only one detail view is available
* Added some border between the viewWrappers when the detail view chooser is hidden

### Screenshot

![grafik](https://user-images.githubusercontent.com/51322092/153574101-d62bb710-d9c0-440e-baca-96dd6c698839.gif)

2022-02-17 10:13 UTC, rumersdorfer reviewed
Works as expected in Ordino Indications/EINS 👍

2022-03-21 12:35 UTC, thinkh requested changes
I haven't tested the functionality. Code-wise it looks fine. Please add a minor comment to the `@extends`. Thanks.

2022-03-21 12:35 UTC, thinkh commented on src/scss/components/_targid.scss
> +      @extend .border-start;
Is `.border-start` a bootstrap class? If yes, I think it is worth to mention it in a comment to avoid confusions.

2022-04-14 12:31 UTC, thinkh approved these changes
Looks good to me. 👍

2022-04-14 12:32 UTC, merged