Adding word "Workbench" to breadcrumb
Caleydo/ordino pull request #369
Opened 2022-03-29 16:24 UTC by dvzacharycutler

![Screenshot from 2022-03-29 18-24-03](https://user-images.githubusercontent.com/87644761/160659569-5382b94b-a47a-4a1d-b682-ee07a34b2c88.png)

Cleaned up some useless conditionals in the code as well

2022-03-30 10:18 UTC, thinkh requested changes

2022-03-30 10:18 UTC, thinkh commented on src/components/breadcrumb/SingleBreadcrumb.tsx
> +            <p className="chevronText flex-grow-1">{`${workbench.name} Workbench`}</p>
Please extract the language string using i18n.

2022-04-04 12:48 UTC, thinkh commented
@dvchristianbors or @dvzacharycutler could you please take a look at the circleci issue? Maybe merging the ordio-2.0 branch her might solve it.

2022-04-04 15:16 UTC, dvchristianbors commented
@thinkh The build is succeeding now.

2022-04-04 15:25 UTC, merged