Add close button to workebenches
Caleydo/ordino pull request #377
Opened 2022-04-19 08:55 UTC by oltionchampari

Closes datavisyn/reprovisyn#283

### Developer Checklist (Definition of Done)

* [ ] Descriptive title for this pull request provided (will be used for release notes later)
* [ ] All acceptance criteria from the issue are met
* [ ] Branch is up-to-date with the branch to be merged with, i.e., develop
* [ ] Code is cleaned up and formatted
* [ ] Code documentation written
* [ ] Unit tests written
* [ ] Tested in Chrome
* [ ] Tested in Firefox
* [ ] Build is successful
* [ ] [Summary of changes](#summary-of-changes) written
* [ ] Wiki documentation written
* [ ] Assign at least one reviewer
* [ ] Assign at least one assignee
* [ ] Add type label (e.g., *bug*, *enhancement*) to this pull request
* [ ] Add next version label (e.g., `next-version: minor`) to this PR following [semver](https://semver.org/)

### Summary of changes

* 

### Screenshots

2022-04-22 12:43 UTC, dvchristianbors approved these changes
Tested in live prototype. Works as intended.

2022-04-25 08:51 UTC, thinkh requested changes
Thanks for your changes.

Please hide/remove the close button from the first workbench, as described in the issue.

Other than that I just have a minor change request.

2022-04-25 08:51 UTC, thinkh commented on src/components/breadcrumb/SingleBreadcrumb.tsx
> +              aria-label="Close"
Please use the I18N language string.

2022-04-27 08:11 UTC, dvchristianbors approved these changes

2022-04-27 08:19 UTC, merged