feat: CLUE support for URL query parameter + refactor public session link
Caleydo/ordino pull request #419
Opened 2022-08-03 06:43 UTC by thinkh

Closes https://github.com/Caleydo/tdp_bi_bioinfodb/issues/1354

Requires https://github.com/datavisyn/tdp_core/pull/762

### Developer Checklist (Definition of Done)

* [x] Descriptive title for this pull request provided (will be used for release notes later)
* [x] All acceptance criteria from the issue are met
* [x] Branch is up-to-date with the branch to be merged with, i.e., develop
* [x] Code is cleaned up and formatted
* [ ] Code documentation written
* [ ] Unit tests written
* [x] Tested in Chrome
* [ ] Tested in Firefox
* [ ] Build is successful -> the build is failing because it depends on https://github.com/datavisyn/tdp_core/pull/762
* [x] [Summary of changes](#summary-of-changes) written
* [ ] Wiki documentation written
* [x] Assign at least one reviewer
* [x] Assign at least one assignee
* [x] Add type label (e.g., *bug*, *enhancement*) to this pull request
* [x] Add next version label (e.g., `next-version: minor`) to this PR following [semver](https://semver.org/)

### Summary of changes

* Refactor how the public session link is generated
* Before it was hard-coded to use the hash property (`#clue_graph=...`)
* With https://github.com/datavisyn/tdp_core/pull/762 the URL can use query parameter (`?clue_graph=...`)
* Now the links are generated using the CLUE graph manager which decides whether hash or query should be used

### Screenshots

![grafik](https://user-images.githubusercontent.com/5851088/182541428-49eea46e-406c-4c66-a36e-6e42a4be92c4.png)

### Context

In order to use the query parameter the following option in ATDPApplication must be set (default is `hash`):

```
const _ = new Ordino({
  cluePropertyHandler: 'query',
});
```

2022-08-03 08:51 UTC, oltionchampari requested changes
Functionality wise, everything works. But I noticed there is a minor difference when loading an  URL with a hash, a hash is added at the end of the query
![grafik](https://user-images.githubusercontent.com/51322092/182566620-eb6ad685-c275-45a4-af28-83430e4d6382.gif)

2022-08-08 08:02 UTC, thinkh commented
@oltionchampari Thanks for testing and pointing it out. The empty hash (i.e., `#` only) is fixed with [datavisyn/tdp_core@`f10ab4d` (#762)](https://github.com/datavisyn/tdp_core/pull/762/commits/f10ab4dd705888df63b36137e9564dc88c241915).

2022-08-11 17:17 UTC, thinkh commented
@oltionchampari please approve this PR so that we can merge the PR. Thanks.

2022-08-16 09:12 UTC, oltionchampari approved these changes

2022-08-16 09:13 UTC, merged